name: Expo Review
on: [pull_request]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download Config To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{ secrets.CONFIG_URL }}
          file-name: 'config.ts'
          location: './'
      - name: Download Config To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{ secrets.GOOGLE_SERVICES }}
          file-name: 'google-services.json'
          location: './'
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: yarn install
      - run: expo publish --release-channel=pr-${{ github.event.pull_request.number }}
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.io/@${{ secrets.EXPO_CLI_USERNAME }}/expo-firebase-template?release-channel=pr-${{ github.event.pull_request.number }}).
